#!/usr/bin/env python3
"""Generate both halves of the batched host OpenGL from tools/glapi.json.

  python3 iris-hostgl/tools/glshim.py
  IRIS_GUEST_TOOLS=path/to/iris-guest-tools python3 iris-hostgl/tools/glshim.py

glapi.json describes every entry point the protocol carries and how each
argument crosses. It is generated by glapi_from_registry.py from the Khronos
OpenGL registry (khronos/gl.xml: declarations and enumerant values) and our
own glapi_annotations.json (the order, which is the op numbering; how
arguments cross; the size tables; where IRIX 6.5's declarations differ from
the registry's). Edit those, not glapi.json. This writes:

  iris-hostgl/src/calls.rs  the decoder: each command's arguments turned back
                            into a call on the host's OpenGL, and the host's
                            size tables

and, when IRIS_GUEST_TOOLS names a checkout of the iris-guest-tools project
(the code that runs in IRIX, kept apart from the emulator), the guest's half:

  gl/glshim_ops.h           the entry point numbers
  gl/glshim_gen.c           one encoder per entry point, and the size tables
                            the encoders need (SGI's pname sizes, glCallLists
                            types, evaluator components)

The wire format is described in iris-guest-tools' gl/glshim.h. Both halves come
from the one description, so they agree on every offset: never change one
without regenerating the other, and commit both. IRIS owns the contract; the
HELLO handshake's PROTOCOL number is what a library and an emulator from
different points check each other with.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))

# Written by hand in iris-guest-tools' gl/glshim_rt.c (or glshim_glx.c), not generated:
# glArrayElement expands into ordinary vertex calls in the guest, so a client
# array is read when the call is made; glGetPointerv answers from the shim's own
# record; glGetString copies a host string into the guest.
GUEST_HANDWRITTEN = {
    "glArrayElement", "glArrayElementEXT", "glGetPointerv", "glGetPointervEXT", "glGetString",
    # glFlush and glFinish are where a GLX pixmap's pixels reach the X pixmap.
    "glFlush", "glFinish",
}

# Calls that must reach the host before returning although no argument says
# so: draws that read client arrays where they are.
FORCE_SYNC = {"glDrawArrays", "glDrawArraysEXT", "glFinish", "glFlush", "glFlushRasterSGIX"}

# Guest-side bookkeeping a stub does before encoding, for the calls whose
# state glArrayElement and glGetPointerv answer from.
GUEST_HOOKS = {
    "glEnableClientState": "hgl_client_state(array, 1);",
    "glDisableClientState": "hgl_client_state(array, 0);",
    "glVertexPointer": "hgl_array_pointer(HGL_ARRAY_VERTEX, size, type, stride, pointer);",
    "glVertexPointerEXT": "hgl_array_pointer(HGL_ARRAY_VERTEX, size, type, stride, pointer);",
    "glNormalPointer": "hgl_array_pointer(HGL_ARRAY_NORMAL, 3, type, stride, pointer);",
    "glNormalPointerEXT": "hgl_array_pointer(HGL_ARRAY_NORMAL, 3, type, stride, pointer);",
    "glColorPointer": "hgl_array_pointer(HGL_ARRAY_COLOR, size, type, stride, pointer);",
    "glColorPointerEXT": "hgl_array_pointer(HGL_ARRAY_COLOR, size, type, stride, pointer);",
    "glIndexPointer": "hgl_array_pointer(HGL_ARRAY_INDEX, 1, type, stride, pointer);",
    "glIndexPointerEXT": "hgl_array_pointer(HGL_ARRAY_INDEX, 1, type, stride, pointer);",
    "glTexCoordPointer": "hgl_array_pointer(HGL_ARRAY_TEXCOORD, size, type, stride, pointer);",
    "glTexCoordPointerEXT": "hgl_array_pointer(HGL_ARRAY_TEXCOORD, size, type, stride, pointer);",
    "glEdgeFlagPointer": "hgl_array_pointer(HGL_ARRAY_EDGEFLAG, 1, GL_UNSIGNED_BYTE, stride, pointer);",
    "glEdgeFlagPointerEXT": "hgl_array_pointer(HGL_ARRAY_EDGEFLAG, 1, GL_UNSIGNED_BYTE, stride, pointer);",
    "glClientActiveTextureARB": "hgl_client_unit(texture);",
    "glDrawBuffer": "hgl_draw_buffer(buf);",
    "glSelectTextureSGIS": "hgl_client_unit(target);",
    "glInterleavedArrays": "hgl_interleaved(format, stride, pointer);",
    "glFeedbackBuffer": "hgl_feedback_pointer = buffer;",
    "glPixelStorei": "hgl_pixel_store(pname, (double)param);",
    "glPixelStoref": "hgl_pixel_store(pname, (double)param);",
    "glPushClientAttrib": "hgl_push_client_attrib(mask);",
    "glPopClientAttrib": "hgl_pop_client_attrib();",
    "glSelectBuffer": "hgl_select_pointer = buffer;",
}

ELEM_BYTES = {"f32": 4, "f64": 8, "i32": 4, "u32": 4, "i16": 2, "u16": 2, "i8": 1, "u8": 1}
RUST_SCALAR = {"u32": "u32", "u8": "u8", "i8": "i8", "i16": "i16", "u16": "u16", "i32": "i32", "f32": "f32", "f64": "f64"}
SCALAR_OF = {
    "GLenum": "u32", "GLboolean": "u8", "GLbitfield": "u32", "GLbyte": "i8", "GLshort": "i16",
    "GLint": "i32", "GLsizei": "i32", "GLubyte": "u8", "GLushort": "u16", "GLuint": "u32",
    "GLfloat": "f32", "GLclampf": "f32", "GLdouble": "f64", "GLclampd": "f64",
}
ARRAY_KINDS = ("inline", "map")      # copied into the command, or by reference

# Colour-index contexts (an overlay visual's; see glshim_glx.c): the host
# draws RGBA only, so an index travels as the red component of an 8-bit
# colour, exactly, and comes back as the overlay pixel. These run before the
# call is encoded, and take it over while an index context is current.
INDEX_HOOKS = {
    **{f"glIndex{t}": "if (hgl_index_mode) { hgl_index((double)c); return; }"
       for t in ("d", "f", "i", "s", "ub")},
    **{f"glIndex{t}v": "if (hgl_index_mode) { hgl_index((double)c[0]); return; }"
       for t in ("d", "f", "i", "s", "ub")},
    "glClearIndex": "if (hgl_index_mode) { hgl_clear_index(c); return; }",
    "glIndexMask": "if (hgl_index_mode) { hgl_index_mask(mask); return; }",
    # An index context's logic op is GL_INDEX_LOGIC_OP (GL_LOGIC_OP); an RGBA
    # one's is GL_COLOR_LOGIC_OP, and it works on the bits of the index.
    "glEnable": "if (hgl_index_mode && cap == GL_LOGIC_OP) cap = GL_COLOR_LOGIC_OP;",
    "glDisable": "if (hgl_index_mode && cap == GL_LOGIC_OP) cap = GL_COLOR_LOGIC_OP;",
    "glIsEnabled": "if (hgl_index_mode && cap == GL_LOGIC_OP) cap = GL_COLOR_LOGIC_OP;",
}

# ... and these after a state query has its answer: an index context answers
# for its index state, which the host does not have.
GUEST_AFTER = {
    "glGetBooleanv": "if (hgl_index_mode) hgl_index_getb(pname, data);",
    "glGetIntegerv": "if (hgl_index_mode) hgl_index_geti(pname, data);",
    "glGetFloatv": "if (hgl_index_mode) hgl_index_getf(pname, data);",
    "glGetDoublev": "if (hgl_index_mode) hgl_index_getd(pname, data);",
}

# The encoders also report what memory the host will read: hgl_ref for a
# by-reference array (its exact size), hgl_ref_image for pixel data, and these
# for the draws that read the client arrays. The host call reads the memory
# itself, so the guest library's versions of these do nothing; they do not
# change the command encoding.
GUEST_REFS = {
    "glDrawArrays": "hgl_ref_draw_arrays(first, count);",
    "glDrawArraysEXT": "hgl_ref_draw_arrays(first, count);",
    "glDrawElements": "hgl_ref_draw_elements(count, type, indices);",
    "glDrawRangeElements": "hgl_ref_draw_elements(count, type, indices);",
}
ADDR_KINDS = ("image", "outimage", "out", "deferred", "array", "drawindices")


def c_count(expr):
    """A count expression over parameter names, as unsigned C, never negative."""
    return f"hgl_nonneg((long)({expr}))"


def rust_count(expr, local):
    def name(m):
        w = m.group(0)
        return f"({local[w]} as i64)" if w in local else w
    body = re.sub(r"[A-Za-z_]\w*", name, expr)
    return f"(({body}) as i64).max(0) as usize"


def layout(fn):
    """Fixed offsets of each parameter in the command, and the fixed size."""
    off = 4
    offs = []
    for p in fn["params"]:
        if p["ptr"] == 0:
            if SCALAR_OF[p["type"]] == "f64":
                off = (off + 7) & ~7
                offs.append(off)
                off += 8
            else:
                offs.append(off)
                off += 4
        elif p.get("kind") in ARRAY_KINDS:
            # count, then an 8-byte address (by reference) or offset (inline)
            offs.append(off)
            off += 12
        else:
            # an 8-byte guest address: 64-bit programs send theirs whole
            offs.append(off)
            off += 8
    return offs, (off + 7) & ~7


def map_count_c(p):
    orders = p["orders"]
    terms = " + ".join(f"({o} - 1) * {s}" for o, s in orders)
    guard = " && ".join(f"{o} > 0" for o, _ in orders)
    return f"(({guard}) ? hgl_nonneg((long)({terms} + hgl_map_components({p['target']}))) : 0)"


def rust_need(p, local):
    """How many elements of array `p` the host's GL reads: the count the
    encoder sends (map_count_c, hgl_size_*, c_count), worked out again from
    the decoded arguments, so a command claiming fewer cannot make the host
    read past what it was given."""
    if p["kind"] == "map":
        orders = p["orders"]
        guard = " && ".join(f"{local[o]} > 0" for o, _ in orders)
        terms = " + ".join(f"({local[o]} as i64 - 1) * ({local[s]} as i64)" for o, s in orders)
        comps = f"super::exec::map_components({local[p['target']]} as u32)"
        return f"(if {guard} {{ ({terms} + {comps}).max(0) as usize }} else {{ 0 }})"
    if "table" in p:
        return f"size_{p['table']}({local[p['key']]} as u32)"
    return rust_count(p["count"], local)


def elem_bytes_c(p):
    if p.get("typed"):
        return f"hgl_calllists_bytes({p['typed']})"
    return str(ELEM_BYTES.get(p["elem"], 1))


def gen_c(api):
    fns = api["functions"]
    enums = api["enums"]
    out = ["/* Generated by iris-hostgl/tools/glshim.py from tools/glapi.json -- do not edit. */",
           "#include <GL/gl.h>", '#include "glshim.h"', '#include "glshim_ops.h"', '#include "glshim_rt.h"', ""]
    for i, fn in enumerate(fns):
        name = fn["name"]
        if name in GUEST_HANDWRITTEN:
            continue
        params = fn["params"]
        offs, fixed = layout(fn)
        args = ", ".join(
            ("const " if p["const"] else "") + p["type"] + " " + "*" * p["ptr"] + p["name"] for p in params
        ) or "void"
        arrays = [(k, p) for k, p in enumerate(params) if p["ptr"] and p.get("kind") in ARRAY_KINDS]
        body = [f"{fn['ret']} {name}({args})", "{", "\tunsigned char *_c;"]
        body.append("\tunsigned _tail = 0, _at;" if arrays else "\tunsigned _tail = 0;")
        # MIPSpro compiles C89: every local is declared before the first
        # statement, so the declarations come first and the sizes after.
        for k, p in arrays:
            body.append(f"\tunsigned _n{k}, _b{k};")
            body.append(f"\tint _r{k};")
        for k, p in arrays:
            if p["kind"] == "map":
                cnt = map_count_c(p)
            elif "table" in p:
                cnt = f"hgl_size_{p['table']}({p['key']})"
            else:
                cnt = c_count(p["count"])
            body.append(f"\t_n{k} = {cnt};")
            body.append(f"\t_b{k} = _n{k} * {elem_bytes_c(p)};")
            body.append(f"\t_r{k} = _b{k} > HGL_INLINE_MAX;")
            body.append(f"\tif (!_r{k}) _tail += (_b{k} + 3) & ~3;")
        if name in INDEX_HOOKS:
            body.append("\t" + INDEX_HOOKS[name])
        if name in GUEST_HOOKS:
            body.append("\t" + GUEST_HOOKS[name])
        body.append(f"\tHGL_CMD(_c, HGL_OP_{name}, HGL_ROUND8({fixed} + _tail));")
        if arrays:
            body.append(f"\t_at = {fixed};")
        byref = []
        for k, p in enumerate(params):
            o = offs[k]
            if p["ptr"] == 0:
                s = SCALAR_OF[p["type"]]
                if s == "f64":
                    body.append(f"\tHGL_PUT_D(_c, {o}, {p['name']});")
                elif s == "f32":
                    body.append(f"\tHGL_PUT_F(_c, {o}, {p['name']});")
                else:
                    body.append(f"\tHGL_PUT_I(_c, {o}, {p['name']});")
            elif p.get("kind") in ARRAY_KINDS:
                body.append(f"\tif (_r{k}) {{")
                body.append(f"\t\tHGL_PUT_I(_c, {o}, _n{k} | HGL_BYREF);")
                body.append(f"\t\tHGL_PUT_A(_c, {o + 4}, {p['name']});")
                body.append(f"\t\thgl_ref((const char *){p['name']}, _b{k});")
                body.append("\t} else {")
                body.append(f"\t\tHGL_PUT_I(_c, {o}, _n{k});")
                body.append(f"\t\tHGL_PUT_A(_c, {o + 4}, _at);")
                body.append(f"\t\tif (_b{k} && {p['name']}) memcpy(_c + _at, {p['name']}, _b{k});")
                body.append(f"\t\t_at += (_b{k} + 3) & ~3;")
                body.append("\t}")
                byref.append(f"_r{k}")
            else:
                body.append(f"\tHGL_PUT_A(_c, {o}, {p['name']});")
                if p.get("kind") == "image" and "dims" in p:
                    dims = list(p["dims"]) + ["1"] * (4 - len(p["dims"]))
                    body.append(
                        f"\thgl_ref_image({p['name']}, {p.get('format_param', '0')}, {p.get('type_param', '0')}, "
                        f"{1 if p.get('bitmap') else 0}, {len(p['dims'])}, {', '.join(dims)});"
                    )
        if name in GUEST_REFS:
            body.append("\t" + GUEST_REFS[name])
        sync = fn["sync"] or name in FORCE_SYNC or any(p.get("kind") == "drawindices" for p in params)
        # A call that only reads this process's memory -- an upload, a draw,
        # a by-reference array -- gives nothing back: it waits only if the
        # encoder could not record exactly what the host reads.
        reads_only = not any(p.get("kind") in ("out", "outimage", "deferred") for p in params)
        if fn["ret"] != "void":
            body.append(f"\treturn ({fn['ret']})hgl_flush();")
        elif sync and reads_only and name not in ("glFinish", "glFlush", "glFlushRasterSGIX"):
            body.append("\thgl_flush_upload();")
        elif sync:
            body.append("\thgl_flush();")
        elif byref:
            body.append(f"\tif ({' || '.join(byref)}) hgl_flush_upload();")
        if name in GUEST_AFTER:
            assert fn["ret"] == "void", name
            body.append("\t" + GUEST_AFTER[name])
        body.append("}")
        out += body + [""]

    # Size tables the encoders use.
    for table, entries in sorted(api["sizes"].items()):
        if table == "CallLists":
            continue  # SGI's helper takes more than the type; the rule is below
        out.append(f"unsigned hgl_size_{table}(GLenum pname)")
        out.append("{")
        out.append("\tswitch (pname) {")
        by_value = {}
        for ename, count in entries.items():
            by_value.setdefault(enums[ename], count)
        for value, count in sorted(by_value.items()):
            out.append(f"\tcase {value:#x}: return {count};")
        out.append("\tdefault: return 1;")
        out.append("\t}")
        out.append("}")
        out.append("")
    # Tables a getter's name implies but SGI's helpers do not have: the setter's.
    return "\n".join(out) + "\n"


def gen_ops(api):
    out = ["/* Generated by iris-hostgl/tools/glshim.py -- do not edit. */", "#ifndef HGL_GLSHIM_OPS_H", "#define HGL_GLSHIM_OPS_H"]
    for i, fn in enumerate(api["functions"]):
        out.append(f"#define HGL_OP_{fn['name']} {i}")
    tables = sorted(t for t in api["sizes"] if t != "CallLists")
    out += [f"extern unsigned hgl_size_{t}(unsigned);" for t in tables]
    out.append("#endif")
    return "\n".join(out) + "\n"


def rust_ptr_type(p):
    elem = p.get("elem", "void")
    t = "c_void" if elem == "void" else elem
    return ("*const " if p["const"] else "*mut ") + t


def gen_rust(api):
    fns = api["functions"]
    enums = api["enums"]
    out = [
        "// Generated by iris-hostgl/tools/glshim.py from tools/glapi.json -- do not edit.",
        "#![allow(clippy::all, dead_code, non_snake_case, unused_parens, unused_variables, unused_mut)]",
        "use super::Exec;",
        "use std::ffi::c_void;",
        "",
        "pub const NAMES: &[&str] = &[",
    ]
    out += [f'    "{fn["name"]}",' for fn in fns]
    out += ["];", ""]

    # Size tables.
    for table, entries in sorted(api["sizes"].items()):
        if table == "CallLists":
            continue
        by_value = {}
        for ename, count in entries.items():
            by_value.setdefault(enums[ename], count)
        out.append(f"pub fn size_{table}(pname: u32) -> usize {{")
        out.append("    match pname {")
        for value, count in sorted(by_value.items()):
            out.append(f"        {value:#x} => {count},")
        out.append("        _ => 1,")
        out.append("    }")
        out.append("}")
    out.append("pub fn get_count(pname: u32) -> usize {")
    out.append("    match pname {")
    seen = set()
    for ename, count in sorted(api["get_multi"].items(), key=lambda kv: enums[kv[0]]):
        v = enums[ename]
        if v in seen:
            continue
        seen.add(v)
        out.append(f"        {v:#x} => {count}, // {ename}")
    out.append("        _ => 1,")
    out.append("    }")
    out.append("}")
    out.append("")

    out.append("/// Run command `op`, whose bytes (header included) are `c`.")
    out.append("pub fn run(x: &mut Exec, op: usize, c: &[u8]) -> Option<u64> {")
    out.append("    match op {")
    for i, fn in enumerate(fns):
        name = fn["name"]
        if name in GUEST_HANDWRITTEN:
            continue
        params = fn["params"]
        offs, _ = layout(fn)
        local = {p["name"]: f"a{k}" for k, p in enumerate(params)}
        # The format and type a pixel call names are the *guest's*, and the
        # host need not have them: GL_ABGR_EXT is SGI's and the Mac refuses it
        # outright. Both go through the executor, which answers with what the
        # host will take and has already put the data in that order.
        fmt_params, typ_params, height_params = {}, {}, set()
        for p in params:
            if p.get("kind") in ("image", "outimage") and p.get("format_param"):
                fmt_params[p["format_param"]] = True
                if p.get("type_param"):
                    typ_params[p["type_param"]] = p["format_param"]
            # SGIX_interlace spreads h source rows over 2h-1 destination rows,
            # so the host is told the taller height for that one call. The
            # second dimension is the height; `gl_height` answers unchanged
            # for every transfer that did not stage one.
            dims = p.get("dims")
            if p.get("kind") == "image" and dims and len(dims) >= 2:
                height_params.add(dims[1])
        # SGIS_texture_select's grouped internal formats are ours, not the
        # Mac's: `gl_internal` answers with what the host will take.
        internal_params = {p["name"] for p in params
                           if p["name"] in ("internalformat", "internalFormat", "components")}
        lines = []
        call_args = []
        call_types = []
        post = []
        for k, p in enumerate(params):
            o = offs[k]
            if p["ptr"] == 0:
                s = SCALAR_OF[p["type"]]
                if s == "f64":
                    lines.append(f"let a{k} = x.f64(c, {o});")
                elif s == "f32":
                    lines.append(f"let a{k} = x.f32(c, {o});")
                else:
                    lines.append(f"let a{k} = x.i32(c, {o}) as {s};")
                name_k = p["name"]
                if name_k in fmt_params:
                    call_args.append(f"x.gl_format(a{k})")
                elif name_k in internal_params:
                    call_args.append(f"x.gl_internal(a{k} as i32) as {s}")
                elif name_k in height_params:
                    call_args.append(f"x.gl_height(a{k} as i32) as {s}")
                elif name_k in typ_params:
                    call_args.append(f"x.gl_type({local[typ_params[name_k]]}, a{k})")
                else:
                    call_args.append(f"a{k}")
                call_types.append(s)
                continue
            kind = p.get("kind")
            if kind in ARRAY_KINDS:
                # The host reads as many elements as the call's own arguments
                # say, not as many as the command carried: `w` holds that many
                # (and slack), and `v` is the part the call means.
                lines.append(f"let n{k} = x.count({rust_need(p, local)})?;")
                if p.get("typed"):
                    lines.append(f"let w{k} = x.arr_typed_padded(c, {o}, {local[p['typed']]} as u32, n{k})?;")
                    lines.append(f"let v{k} = &w{k}[..];")
                    call_args.append(f"x.ptr_of(v{k}) as *const c_void")
                    call_types.append("*const c_void")
                else:
                    e = p["elem"]
                    lines.append(f"let w{k} = x.arr_padded::<{e}>(c, {o}, n{k})?;")
                    lines.append(f"let v{k} = &w{k}[..n{k}];")
                    call_args.append(f"x.ptr_of(v{k})")
                    call_types.append(f"*const {e}")
                lines.append(f"let a{k} = 0u64;")
                continue
            lines.append(f"let a{k} = x.addr(c, {o});")
            if kind == "out":
                e = p["elem"] if p.get("elem") not in (None, "void") else "u8"
                if "count" in p:
                    cnt = rust_count(p["count"], local)
                elif "table" in p:
                    cnt = f"size_{p['table']}({local[p['key']]} as u32)"
                elif "get" in p:
                    cnt = f"get_count({local[p['get']]} as u32)"
                elif "pixelmap" in p:
                    cnt = f"x.pixelmap_size({local[p['pixelmap']]} as u32)"
                elif "mapquery" in p:
                    t, q = p["mapquery"]
                    cnt = f"x.mapquery_count({local[t]} as u32, {local[q]} as u32)"
                else:
                    cnt = "{ x.unsupported(" + str(i) + "); 0 }"
                # Guest-controlled counts size host allocations: refused past a
                # sane limit rather than allowed to abort the emulator.
                lines.append(f"let c{k} = {cnt};")
                lines.append(f"let n{k} = x.count(c{k})?;")
                lines.append(f"let mut o{k} = vec![0 as {e}; n{k}.max(1) + 16];")
                call_args.append(f"o{k}.as_mut_ptr()")
                call_types.append(f"*mut {e}")
                post.append(f"x.put::<{e}>(a{k}, &o{k}[..n{k}])?;")
            elif kind in ("image", "outimage"):
                fmt = local.get(p.get("format_param", ""), "0u32")
                typ = local.get(p.get("type_param", ""), "0u32")
                bitmap = "true" if p.get("bitmap") else "false"
                if "dims" in p:
                    dims = ", ".join(local[d] + " as i32" if d in local else d for d in p["dims"])
                    dims = f"&[{dims}]"
                else:
                    extra = ", ".join(f"{local[n]} as i32" for n in ("target", "level") if n in local)
                    lines.append(f"let d{k} = x.dims_from(\"{p['dims_from']}\", &[{extra}]);")
                    dims = f"&d{k}"
                outp = "true" if kind == "outimage" else "false"
                lines.append(f"let p{k} = x.image(a{k}, {dims}, {fmt} as u32, {typ} as u32, {bitmap}, {outp})?;")
                call_args.append(f"p{k} as {rust_ptr_type(p)}")
                call_types.append(rust_ptr_type(p))
            elif kind in ("array", "deferred", "drawindices"):
                call_args.append(f"a{k}")
                call_types.append("u64")
        # Calls that the executor handles itself.
        special = special_call(name, params, local)
        if special:
            lines.append(special)
        else:
            ret = fn["ret"]
            rust_ret = "" if ret == "void" else f" -> {SCALAR_OF.get(ret, 'u32')}"
            if re.sub(r"(EXT|SGIX|SGIS|SGI)$", "", name) in FRAMEBUFFER_READERS:
                lines.append("x.resolve_read();")
            guard = GUARDED.get(name)
            if guard:
                lines.append(f"if !{guard} {{")
            lines.append(f"let f = x.func({i})?;")
            lines.append(
                f"let g: extern \"C\" fn({', '.join(call_types)}){rust_ret} = unsafe {{ std::mem::transmute(f) }};"
            )
            if ret == "void":
                lines.append(f"g({', '.join(call_args)});")
                if guard:
                    lines.append("}")
                # The state queries go past the executor on the way back, so
                # that a limit the host reports but this library cannot stand
                # behind is answered with one it can (Exec::get_limit).
                if name in ("glGetBooleanv", "glGetDoublev", "glGetFloatv", "glGetIntegerv"):
                    lines.append("x.get_limit(a0, &mut o1);")
                lines += post
                lines.append("x.image_done();")
                lines.append("Some(0)")
            else:
                lines.append(f"let r = g({', '.join(call_args)});")
                lines += post
                lines.append("x.image_done();")
                lines.append("Some(r as u64)")
        out.append(f"        {i} => {{ // {name}")
        out += ["            " + l for l in lines]
        out.append("        }")
    out.append("        _ => { x.unsupported(op); Some(0) }")
    out.append("    }")
    out.append("}")
    return "\n".join(out) + "\n"


# Calls the emulation layer may claim: it takes them when the target or the
# enumerant is one the Mac has not got, and otherwise they go to the Mac. The
# value is the condition, in terms of the decoded arguments.
GUARDED = {
    "glColorTable": "x.color_table(a0, a2, p5 as *const u8, a3, a4)",
    "glColorTableSGI": "x.color_table(a0, a2, p5 as *const u8, a3, a4)",
    "glTexParameterfv": "x.tex_parameter(a1, &v2)",
    "glGetTexParameterfv": "x.get_tex_parameter(a1, &mut o2)",
    # The scalar forms carry SGIS_texture_filter4's filter mode, which the Mac
    # would refuse: the shader does those taps itself.
    "glTexParameteri": "x.tex_parameter(a1, &[a2 as f32])",
    "glTexParameterf": "x.tex_parameter(a1, &[a2])",
    "glTexFilterFuncSGIS": "x.tex_filter_func(a1, &v3)",
    "glDrawPixels": "x.draw_pixels(a0, a1, a2, a3, p4 as *const c_void)",
    "glTexImage2D": "x.tex_image_2d(a0, a1, a2, a3, a4, a5, x.gl_format(a6), x.gl_type(a6, a7), p8 as *const c_void)",
    "glFogf": "x.fog(a0, &[a1])",
    "glFogi": "x.fog(a0, &[a1 as f32])",
    "glFogfv": "x.fog(a0, &v1)",
}

# Calls that read the framebuffer: a multisampled drawable is resolved first.
FRAMEBUFFER_READERS = (
    "glReadPixels", "glCopyPixels", "glAccum", "glCopyTexImage1D", "glCopyTexImage2D",
    "glCopyTexSubImage1D", "glCopyTexSubImage2D", "glCopyTexSubImage3D",
    "glCopyColorTable", "glCopyColorSubTable", "glCopyConvolutionFilter1D", "glCopyConvolutionFilter2D",
)


def special_call(name, params, local):
    """The body for calls the executor handles itself, or None."""
    a = [local[p["name"]] for p in params]
    base = re.sub(r"(ARB|EXT|SGIX|SGIS|SGI)$", "", name)
    if name == "glPixelStorei":
        return f"x.pixel_store({a[0]}, {a[1]} as f32); Some(0)"
    if name == "glPixelStoref":
        return f"x.pixel_store({a[0]}, {a[1]}); Some(0)"
    if name in ("glEnableClientState", "glDisableClientState"):
        return f"x.client_state({a[0]}, {'true' if name.startswith('glEnable') else 'false'}); Some(0)"
    if name == "glGetError":
        return "Some(x.get_error() as u64)"
    # The accumulation buffer is the executor's (accum.rs): framebuffer
    # objects have none.
    if name == "glAccum":
        return f"x.accum({a[0]}, {a[1]}); Some(0)"
    if name == "glClearAccum":
        return f"x.clear_accum({a[0]}, {a[1]}, {a[2]}, {a[3]}); Some(0)"
    if name == "glClear":
        return f"x.clear({a[0]}); Some(0)"
    # SGIS_multitexture is ARB_multitexture under older names, and the Mac has
    # only the ARB/core ones: the executor maps the unit and calls those.
    if name == "glSelectTextureSGIS":
        return f"x.select_texture({a[0]}); Some(0)"
    if name == "glClientActiveTextureARB":
        return f"x.client_active_texture({a[0]}); Some(0)"
    if name == "glMTexCoord2fSGIS":
        return f"x.mtex_coord2f({a[0]}, {a[1]}, {a[2]}); Some(0)"
    if name == "glMTexCoord2fvSGIS":
        return "x.mtex_coord2f(%s, v1[0], v1[1]); Some(0)" % a[0]
    if name in ("glEnable", "glDisable"):
        return f"x.set_enable({a[0]}, {'true' if name == 'glEnable' else 'false'}); Some(0)"
    if name == "glIsEnabled":
        return f"Some(x.is_enabled({a[0]}) as u64)"
    if name in ("glTexEnvi", "glTexEnvf"):
        return f"x.tex_env({a[0]}, {a[1]}, {a[2]} as u32); Some(0)"
    if base == "glBindTexture":
        return f"x.bind_texture({a[0]}, {a[1]}); Some(0)"
    if base == "glFogFunc":
        return f"x.fog_func(&v1); Some(0)"
    if name == "glTexImage4DSGIS":
        # Each translation is taken first: they borrow the executor, and the
        # call that uses them borrows it too.
        return ("let internal = x.gl_internal(a2 as i32);\n"
                "let fmt = x.gl_format(a8);\n"
                "let ty = x.gl_type(a8, a9);\n"
                "x.tex_image_4d(a1, internal, a3, a4, a5, a6, a7, fmt, ty, p10 as *const c_void);\n"
                "Some(0)")
    if name == "glPixelTexGenSGIX":
        return f"x.pixel_tex_gen({a[0]}); Some(0)"
    if name == "glBegin":
        return f"x.begin({a[0]}); Some(0)"
    if name == "glEnd":
        return "x.end(); Some(0)"
    if re.match(r"^glSpriteParameter[fi]v?SGIX$", name):
        # The integer vector form arrives as i32s and the state is floats.
        if not params[1]["ptr"]:
            arg = f"&[{a[1]} as f32]"
        elif params[1].get("elem") == "f32":
            arg = "&v1"
        else:
            arg = "&v1.iter().map(|v| *v as f32).collect::<Vec<f32>>()"
        return f"x.sprite_parameter({a[0]}, {arg}); Some(0)"
    if base == "glDetailTexFunc":
        return f"x.detail_func(&v2); Some(0)"
    if base == "glSharpenTexFunc":
        return f"x.sharpen_func(&v2); Some(0)"
    if base == "glReferencePlane":
        return f"x.reference_plane(&v0); Some(0)"
    if name in ("glDrawBuffer", "glReadBuffer"):
        return f"x.color_buffer({'true' if name == 'glDrawBuffer' else 'false'}, {a[0]}); Some(0)"
    if name == "glPolygonOffsetEXT":
        return f"x.polygon_offset_ext({a[0]}, {a[1]}); Some(0)"
    if base == "glDrawArrays":
        return f"x.draw_arrays({a[0]}, {a[1]}, {a[2]}); Some(0)"
    if name == "glDrawElements":
        return f"x.draw_elements({a[0]}, {a[1]}, {a[2]}, {a[3]}); Some(0)"
    if name == "glDrawRangeElements":
        return f"x.draw_elements({a[0]}, {a[3]}, {a[4]}, {a[5]}); Some(0)"
    if name == "glRenderMode":
        return f"Some(x.render_mode({a[0]}) as u32 as u64)"
    if name == "glFeedbackBuffer":
        return f"x.feedback_buffer({a[0]}, {a[1]}, {a[2]}); Some(0)"
    if name == "glSelectBuffer":
        return f"x.select_buffer({a[0]}, {a[1]}); Some(0)"
    if name == "glInterleavedArrays":
        return f"x.interleaved({a[0]}, {a[1]}, {a[2]}); Some(0)"
    m = re.match(r"^gl(Vertex|Normal|Color|Index|TexCoord|EdgeFlag)Pointer$", base)
    if m:
        pn = [p["name"] for p in params]
        size = local["size"] if "size" in pn else ("3" if m.group(1) == "Normal" else "1")
        typ = local["type"] if "type" in pn else "0x1401"
        which = ["Vertex", "Normal", "Color", "Index", "TexCoord", "EdgeFlag"].index(m.group(1))
        return f"x.array_pointer({which}, {size} as i32, {typ} as u32, {local['stride']} as i32, {local['pointer']}); Some(0)"
    return None


def main():
    crate = os.path.dirname(HERE)
    api = json.load(open(os.path.join(HERE, "glapi.json")))
    open(os.path.join(crate, "src", "calls.rs"), "w").write(gen_rust(api))
    guest_tools = os.environ.get("IRIS_GUEST_TOOLS")
    if guest_tools:
        guest = os.path.join(guest_tools, "gl")
        if not os.path.isfile(os.path.join(guest, "glshim.h")):
            raise SystemExit(f"glshim.py: {guest_tools} is not an iris-guest-tools checkout (no gl/glshim.h)")
        open(os.path.join(guest, "glshim_ops.h"), "w").write(gen_ops(api))
        open(os.path.join(guest, "glshim_gen.c"), "w").write(gen_c(api))
    n = len(api["functions"])
    print(f"{n} entry points: {n - len(GUEST_HANDWRITTEN)} generated, {len(GUEST_HANDWRITTEN)} written by hand")
    if not guest_tools:
        print("glshim.py: the guest's encoders were not written: set IRIS_GUEST_TOOLS to an iris-guest-tools checkout")


if __name__ == "__main__":
    main()
