#!/usr/bin/env python3
"""Stamp and verify bench/prebuilt/ against the sources it was built from.

Byte-comparing the checked-in guest image against a fresh build does not work,
and CI proved it: the image is compiled with -g, so DWARF records the build
directory — a runner's `/home/runner/work/iris/iris` is never a developer's
`~/repos/iris` — and the toolchain version differs on top of that. The bytes
legitimately differ between two correct builds of identical source.

What must not drift is the *pairing*: the checked-in image and the sources it
was built from. That is what this hashes, so verification needs no cross
toolchain and no compilation at all — just the files.

What it deliberately does not check is that the image *works*; a hash cannot
tell you that. The embedded-runner test does, by running the suite out of the
binary the image is linked into and requiring 100% accuracy against the golden
checksums compiled into it.

    prebuilt-stamp.py --write    after `make prebuilt`, records the digest
    prebuilt-stamp.py --check    fails if the sources have moved since
"""

import hashlib
import pathlib
import sys

BENCH = pathlib.Path(__file__).resolve().parent
ROOT = BENCH.parent
STAMP = BENCH / "prebuilt" / "PROVENANCE"
ELF = BENCH / "prebuilt" / "irisbench.elf"

#: Everything irisbench.elf is built from. `cpu-tests/harness` is in here
#: because the toolchain probe, the console, the startup code and the exception
#: dispatcher are shared with that suite — changing them changes this image.
SOURCES = [
    ("bench/harness", "*"),
    ("bench/kernels", "*"),
    ("bench/golden", "golden.h"),
    ("bench", "Makefile"),
    ("cpu-tests/harness", "*"),
    ("cpu-tests", "toolchain.mk"),
]


def inputs():
    """Every source file, sorted, so the digest does not depend on readdir order."""
    out = []
    for subdir, pattern in SOURCES:
        for p in sorted((ROOT / subdir).glob(pattern)):
            if p.is_file():
                out.append(p)
    return sorted(out)


def digest():
    """sha256 over each input's path *and* contents.

    The path is folded in so that adding or renaming a kernel changes the
    digest even when the bytes of every individual file are unchanged.
    """
    h = hashlib.sha256()
    for p in inputs():
        h.update(str(p.relative_to(ROOT)).encode())
        h.update(b"\0")
        h.update(p.read_bytes())
        h.update(b"\0")
    return h.hexdigest()


def elf_sha():
    return hashlib.sha256(ELF.read_bytes()).hexdigest() if ELF.exists() else "(missing)"


def recorded():
    if not STAMP.exists():
        return None
    for line in STAMP.read_text().splitlines():
        if line.startswith("sources"):
            return line.split()[-1]
    return None


def write():
    STAMP.write_text(
        "# Generated by prebuilt-stamp.py; see it for what these mean.\n"
        "#\n"
        "# `sources` is the digest of everything irisbench.elf is built from.\n"
        "# CI compares it and fails if the image was not refreshed alongside a\n"
        "# source change. The ELF's own hash is informational only — two correct\n"
        "# builds of identical source differ, because -g records the build path.\n"
        f"sources  sha256 {digest()}\n"
        f"image    sha256 {elf_sha()}  {ELF.stat().st_size if ELF.exists() else 0} bytes\n"
        f"inputs   {len(inputs())} files\n"
    )
    print(f"prebuilt-stamp: recorded {len(inputs())} inputs")


def check():
    want, got = recorded(), digest()
    if want is None:
        sys.exit("prebuilt-stamp: no digest recorded — run `make -C bench prebuilt`")
    if not ELF.exists():
        sys.exit(f"prebuilt-stamp: {ELF} is missing")
    if want != got:
        sys.exit(
            "prebuilt-stamp: bench/prebuilt/irisbench.elf is stale.\n"
            f"  recorded sources {want}\n"
            f"  current  sources {got}\n"
            "  The guest sources changed without the checked-in image being\n"
            "  refreshed. `iris` links that image in, and accuracy is scored\n"
            "  against golden checksums compiled into it — a stale image reports\n"
            "  failures to users that are not real.\n"
            "  Fix: make -C bench prebuilt, and commit bench/prebuilt/."
        )
    print(f"prebuilt-stamp: image matches its {len(inputs())} sources")


if __name__ == "__main__":
    if "--write" in sys.argv:
        write()
    elif "--check" in sys.argv:
        check()
    else:
        sys.exit(__doc__)
