/* fpvectors.h — GENERATED by gen/fpvectors.py. Do not edit.
 *
 * IEEE-754 expectations computed with exact rational arithmetic on the host,
 * never read off any FPU. Regenerate with `make vectors`. See docs/oracle.md
 * for why the suite insists on this.
 *
 * `flags` is the set of FCSR exception bits (FP_I/FP_U/FP_O/FP_Z/FP_V) the
 * operation must raise. Results that are NaN or subnormal are deliberately
 * absent: NaN payloads are implementation-defined, and a subnormal result is
 * an Unimplemented Operation on an R4400 rather than an arithmetic result at
 * all — tests/fpu/fpu_denorm.c covers those with the manual quoted alongside.
 */
#ifndef FPVECTORS_H
#define FPVECTORS_H

#include "testlib.h"

struct fpvs2 { u32 a, b, r; u32 flags; };
struct fpvs1 { u32 a, r; u32 flags; };
struct fpvd2 { u64 a, b, r; u32 flags; };
struct fpvd1 { u64 a, r; u32 flags; };
struct fpvcvt_s32 { u32 in; s32 rn, rz, rp, rm; };
struct fpvcvt_s64 { u32 in; s64 rn, rz, rp, rm; };
struct fpvcvt_d32 { u64 in; s32 rn, rz, rp, rm; };
struct fpvcvt_d64 { u64 in; s64 rn, rz, rp, rm; };
struct fpvrms { u32 a, b, rn, rz, rp, rm; };
struct fpvrmd { u64 a, b, rn, rz, rp, rm; };
struct fpvfromi32 { s32 in; u32 s; u32 sflags; u64 d; u32 dflags; };
struct fpvfromi64 { s64 in; u32 s; u32 sflags; u64 d; u32 dflags; };

extern const struct fpvs2 fpv_add_s[];
#define FPV_ADD_S_N 16
extern const struct fpvs2 fpv_sub_s[];
#define FPV_SUB_S_N 16
extern const struct fpvs2 fpv_mul_s[];
#define FPV_MUL_S_N 16
extern const struct fpvs2 fpv_div_s[];
#define FPV_DIV_S_N 13
extern const struct fpvs1 fpv_sqrt_s[];
#define FPV_SQRT_S_N 7
extern const struct fpvrms fpv_rm_div_s[];
#define FPV_RM_DIV_S_N 4
extern const struct fpvrms fpv_rm_mul_s[];
#define FPV_RM_MUL_S_N 2
extern const struct fpvcvt_s32 fpv_cvt_s32[];
#define FPV_CVT_S32_N 15
extern const struct fpvcvt_s64 fpv_cvt_s64[];
#define FPV_CVT_S64_N 15
extern const struct fpvd2 fpv_add_d[];
#define FPV_ADD_D_N 16
extern const struct fpvd2 fpv_sub_d[];
#define FPV_SUB_D_N 16
extern const struct fpvd2 fpv_mul_d[];
#define FPV_MUL_D_N 16
extern const struct fpvd2 fpv_div_d[];
#define FPV_DIV_D_N 13
extern const struct fpvd1 fpv_sqrt_d[];
#define FPV_SQRT_D_N 7
extern const struct fpvrmd fpv_rm_div_d[];
#define FPV_RM_DIV_D_N 4
extern const struct fpvrmd fpv_rm_mul_d[];
#define FPV_RM_MUL_D_N 2
extern const struct fpvcvt_d32 fpv_cvt_d32[];
#define FPV_CVT_D32_N 15
extern const struct fpvcvt_d64 fpv_cvt_d64[];
#define FPV_CVT_D64_N 15
extern const struct fpvfromi32 fpv_from_i32[];
#define FPV_FROM_I32_N 11
extern const struct fpvfromi64 fpv_from_i64[];
#define FPV_FROM_I64_N 8

#endif /* FPVECTORS_H */
