#!/usr/bin/env python3
"""Generate monomorphised REX3 draw shaders from the saved rex-jit corpus.

Reads the `IRXP` profile the emulator writes on exit (default
`$HOME/.iris/rex-jit-profile.bin`) and emits a Rust source file containing one
wrapper per distinct draw mode, plus a sorted key -> function-pointer table that
`Rex3` loads into its shader map at startup.

Each wrapper instantiates the *existing* generic draw pipeline with `ConstMode`,
so every mode field becomes a compile-time literal and LLVM folds the branches
away — the same specialisation Cranelift performs, done ahead of time.

**This script deliberately does not decode the drawmode bits itself.** The
canonical form (the FASTCLEAR fold, dead blend inputs, host fields) lives in one
place, `rex3_shape::unpack`, which is a `const fn`; the generated code calls it
in const position so the constants are derived by the same code the runtime
uses. A Python reimplementation would be a second decoder free to drift, and the
whole point of the refactor is that there is only one.

Usage:
    tools/gen_rex3_shaders.py [profile ...] -o src/dev/ng1/rex3_shaders.rs

With no profile argument it reads $IRIS_REX_JIT_PROFILE, else
$HOME/.iris/rex-jit-profile.bin. Multiple profiles are merged and de-duplicated,
so corpora collected from different workloads can be combined.
"""

import argparse
import os
import struct
import sys
from pathlib import Path

MAGIC = b"IRXP"
VERSION = 2
HEADER_LEN = 9  # magic(4) + version(1) + count(4)
ENTRY_LEN = 12  # dm0, dm1, cm — all u32 LE


def default_profile() -> Path:
    env = os.environ.get("IRIS_REX_JIT_PROFILE")
    if env:
        return Path(env)
    home = os.environ.get("HOME")
    if home:
        return Path(home) / ".iris" / "rex-jit-profile.bin"
    return Path("rex-jit-profile.bin")


def read_profile(path: Path) -> list[tuple[int, int, int]]:
    """Parse one IRXP v2 profile into (dm0, dm1, cm) triples."""
    try:
        data = path.read_bytes()
    except OSError as e:
        print(f"warning: cannot read {path}: {e}", file=sys.stderr)
        return []

    if len(data) < HEADER_LEN or data[:4] != MAGIC:
        print(f"warning: {path} is not an IRXP profile, skipping", file=sys.stderr)
        return []
    if data[4] != VERSION:
        print(
            f"warning: {path} is IRXP v{data[4]}, expected v{VERSION}, skipping",
            file=sys.stderr,
        )
        return []

    count = struct.unpack_from("<I", data, 5)[0]
    entries = []
    for i in range(count):
        off = HEADER_LEN + i * ENTRY_LEN
        if off + ENTRY_LEN > len(data):
            print(
                f"warning: {path} truncated after {i} of {count} entries",
                file=sys.stderr,
            )
            break
        entries.append(struct.unpack_from("<III", data, off))
    return entries


# Shapes always emitted, whatever the corpus holds.
#
# The corpus records what a *guest* drew, so shapes exercised only by the
# in-tree benchmarks and tests never appear in it — and without a precompiled
# shader those benchmarks silently measure the generic fallback instead of the
# specialised path they claim to compare. Seeding them here keeps the comparison
# honest and survives a corpus regenerated on any machine.
#
# Keep this list small and justified: every entry is a monomorphisation.
SEED_SHAPES: list[tuple[int, int, int]] = [
    # gfifo_pressure_sweep: DRAW/SPAN at RGB24+SRC, CIDMATCH=0xF, in its three
    # variants — flat, Gouraud (SHADE), and ZPATTERN-masked (SHADE|ZPAT|LEN32).
    (0x0000_0102, 0x3000_F019, 0x0000_1E00),
    (0x0004_0102, 0x3000_F019, 0x0000_1E00),
    (0x0004_9102, 0x3000_F019, 0x0000_1E00),
]


# Order must match ConstMode's const parameter list in rex3_generic.rs.
FIELDS = [
    "opcode", "planes", "drawdepth", "dblsrc", "rgbmode", "dither", "logicop",
    "compare", "blend", "backblend", "blendalpha", "fastclear", "colorhost",
    "alphahost", "enzpattern", "enlspattern", "zpopaque", "lsopaque", "cidtest",
    "shade", "ciclamp", "stoponx", "stopony", "skipfirst", "skiplast",
    "lsadvlast", "length32", "lronly", "ystride", "endptfilter", "adrmode",
    "xyoffset", "yflip", "ensmask", "cid_mask", "sfactor", "dfactor",
    "rwpacked", "hostdepth", "rwdouble", "swapendian",
]


def emit(entries: list[tuple[int, int, int]], source: str) -> str:
    out: list[str] = []
    w = out.append

    w("// @generated by tools/gen_rex3_shaders.py — do not edit.")
    w(f"// Source: {source}")
    w("//")
    w("// One wrapper per draw mode seen in the corpus, each instantiating the")
    w("// generic pipeline with every mode field as a compile-time constant.")
    w("// The constants are derived by calling `rex3_shape::unpack` in const")
    w("// position, so this file cannot disagree with the runtime decoder.")
    w("//")
    w("// Regenerate after collecting a fatter corpus:")
    w("//     tools/gen_rex3_shaders.py -o src/dev/ng1/rex3_shaders.rs")
    w("")
    w("use crate::rex3::Rex3Context;")
    w("use crate::rex3_generic::{draw_with_fb, ConstMode, Framebuffers};")
    w("use crate::rex3_shape::unpack;")
    w("")
    w("/// A specialised draw entry point.")
    w("///")
    w("/// **Identical to the Cranelift shader ABI** (`CompiledShader::entry`), so")
    w("/// an LLVM-compiled shader and a Cranelift one are interchangeable at the")
    w("/// dispatch site: `(ctx, fb_rgb, fb_aux)`, `extern \"C\"`.")
    w("pub type ShaderFn = unsafe extern \"C\" fn(*mut Rex3Context, *mut u32, *mut u32);")
    w("")

    # De-duplicate by the canonical mode, not the raw triple: two register
    # combinations that fold to the same mode need only one instantiation. We
    # cannot compute the fold here (that is unpack's job, in Rust), so we
    # de-duplicate on the raw triple and let identical instantiations collapse
    # at link time via ICF.
    seen = sorted(set(entries))

    for dm0, dm1, cm in seen:
        name = f"shader_{dm0:08x}_{dm1:08x}_{cm:08x}"
        args = ",\n        ".join(
            f"{{ unpack({dm0:#010x}, {dm1:#010x}, {cm:#010x}).{f} }}" for f in FIELDS
        )
        w(f"/// dm0={dm0:#010x} dm1={dm1:#010x} cm={cm:#010x}")
        w(f"unsafe extern \"C\" fn {name}(")
        w(f"    ctx: *mut Rex3Context,")
        w(f"    fb_rgb: *mut u32,")
        w(f"    fb_aux: *mut u32,")
        w(f") {{")
        w(f"    let m: ConstMode<")
        w(f"        {args},")
        w(f"    > = ConstMode;")
        w(f"    let fb = Framebuffers {{ rgb: fb_rgb, aux: fb_aux }};")
        w(f"    draw_with_fb(unsafe {{ &mut *ctx }}, &fb, &m);")
        w("}")
        w("")

    w("/// Sorted by key, so the lookup can binary-search.")
    w("///")
    w("/// Key is the raw `(dm0, dm1, clipmode & CLIPMODE_JIT_KEY_MASK)` triple —")
    w("/// the same key the Cranelift shader cache uses, so both stores answer the")
    w("/// same question and a table hit can pre-empt a JIT compile.")
    w(f"pub static SHADERS: &[((u32, u32, u32), ShaderFn)] = &[")
    for dm0, dm1, cm in seen:
        name = f"shader_{dm0:08x}_{dm1:08x}_{cm:08x}"
        w(f"    (({dm0:#010x}, {dm1:#010x}, {cm:#010x}), {name}),")
    w("];")
    w("")
    w("/// Look up a specialised shader for this draw mode.")
    w("#[inline]")
    w("pub fn lookup(dm0: u32, dm1: u32, cm: u32) -> Option<ShaderFn> {")
    w("    SHADERS")
    w("        .binary_search_by_key(&(dm0, dm1, cm), |&(k, _)| k)")
    w("        .ok()")
    w("        .map(|i| SHADERS[i].1)")
    w("}")

    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("profiles", nargs="*", type=Path, help="IRXP profile(s) to read")
    ap.add_argument("-o", "--output", type=Path, required=True, help="Rust file to write")
    args = ap.parse_args()

    paths = args.profiles or [default_profile()]
    entries: list[tuple[int, int, int]] = list(SEED_SHAPES)
    print(f"seed: {len(SEED_SHAPES)} always-emitted shapes", file=sys.stderr)
    for p in paths:
        got = read_profile(p)
        print(f"{p}: {len(got)} entries", file=sys.stderr)
        entries.extend(got)

    unique = sorted(set(entries))
    print(
        f"{len(entries)} entries -> {len(unique)} unique triples",
        file=sys.stderr,
    )

    source = ", ".join(str(p) for p in paths)
    args.output.write_text(emit(entries, source))
    print(f"wrote {args.output} ({len(unique)} shaders)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
