; Inno Setup script for IRIS (Windows).
; Defaults to a per-user install into %LocalAppData% (no admin required), but the
; user can choose "install for all users" (elevates to admin), which installs
; into C:\Program Files\IRIS — the {auto*} constants follow whichever they pick.
;
; Build:
;   iscc /DMyAppVersion=2025-06-09-02-00 /DSourceDir=path\to\build /DAssetsDir=path\to\icons installer\iris-gui.iss

#ifndef MyAppVersion
  #define MyAppVersion "0.0.0-dev"
#endif

; Directory containing iris-gui.exe.
#ifndef SourceDir
  #define SourceDir "..\target\release"
#endif

; Directory containing icon.ico.
#ifndef AssetsDir
  #define AssetsDir "..\iris-gui\assets\icons"
#endif

; Combined license file (generated by CI, or pass manually). IRIS and the CHD
; backend are both BSD-3-Clause as of libchdman-rs 0.288.8.
#ifndef LicenseFile
  #define LicenseFile "..\COMBINED-LICENSE.txt"
#endif

; Target architecture of the bundled iris-gui.exe. CI passes /DTargetArch=x64 or
; /DTargetArch=arm64; the installer then refuses to run on the wrong arch (the
; payload is arch-specific). Maps to the Inno Setup architecture identifiers.
#ifndef TargetArch
  #define TargetArch "x64"
#endif
#if TargetArch == "arm64"
  #define ArchIdentifier "arm64"
#else
  #define ArchIdentifier "x64compatible"
#endif

; CPU variant of the bundled iris-gui.exe. CI passes /DR5000=1 for the R5000
; build; without it this is the default R4400 build. The two get distinct AppIds,
; names, and default folders so both can be installed side by side — same binary
; layout, different emulated CPU (a compile-time choice, so they can't be one
; installer with a switch).
#ifdef R5000
  #define MyAppName "IRIS (R5000)"
  #define MyAppId "{{2B6E5D74-9C41-4A83-B7F0-5E1C8D2A64B9}"
#else
  #define MyAppName "IRIS"
  #define MyAppId "{{A7F2C91E-3D8B-4F5A-8E2C-1B9D6A3E8F42}"
#endif
#define MyAppPublisher "Dani Sarfati"
#define MyAppURL "https://github.com/danifunker/iris"
#define MyAppExeName "iris-gui.exe"

[Setup]
; Stable AppIds — do not change across releases (an AppId change orphans the
; previous install's uninstall entry instead of upgrading it).
AppId={#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}/releases
LicenseFile={#LicenseFile}
; Restrict to the arch of the bundled binary (x64compatible covers x64 hosts and
; x64-on-arm64 emulation; arm64 is native ARM64). 64-bit install mode either way.
ArchitecturesAllowed={#ArchIdentifier}
ArchitecturesInstallIn64BitMode={#ArchIdentifier}
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
; Use the "auto" Program Files constant so the destination follows the install
; mode the user picks via PrivilegesRequiredOverridesAllowed: an all-users
; (elevated) install lands in C:\Program Files\IRIS, a per-user install in
; %LocalAppData%\Programs\IRIS. A literal {localappdata} would force the per-user
; folder even when the user chose "install for all users".
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
DefaultGroupName={#MyAppName}
DisableDirPage=no
AllowNoIcons=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
OutputBaseFilename=IRIS-Setup
Compression=lzma2
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Files]
Source: "{#SourceDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#AssetsDir}\icon.ico"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
; Both licenses ship with the installed app so users can read them post-install.
Source: "{#LicenseFile}"; DestDir: "{app}"; DestName: "LICENSE.txt"; Flags: ignoreversion skipifsourcedoesntexist

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; Flags: nowait postinstall skipifsilent

; ───────────────────────────────────────────────────────────────────────────
; Npcap handling — PCAP installer variant only (compiled with `iscc /DPcap=1`).
; The standard/lightning installer has no [Code] section and is unchanged.
;
; PCAP bridged networking needs a WinPcap-compatible driver (Npcap). We do NOT
; bundle it (proprietary, redistribution forbidden) and we never silently
; download it. Instead, when Npcap is missing we show a page that OPENS the
; official npcap.com download page in the user's browser; the user installs
; Npcap themselves (its installer has its own UAC), then clicks Next to re-check.
; The page is skipped entirely when Npcap is already present. The IRIS installer
; stays per-user/no-admin throughout.
#ifdef Pcap
[Code]
var
  NpcapPage: TWizardPage;

{ True when a WinPcap-compatible driver (Npcap, or a legacy WinPcap) is present.
  Checks the wpcap.dll the `pcap` crate links against and the npcap service. }
function NpcapInstalled(): Boolean;
begin
  Result := FileExists(ExpandConstant('{sys}\Npcap\wpcap.dll')) or
            FileExists(ExpandConstant('{sys}\wpcap.dll')) or
            RegKeyExists(HKLM, 'SYSTEM\CurrentControlSet\Services\npcap');
end;

{ Open the official Npcap download page in the user's default browser. }
procedure OpenNpcapSite(Sender: TObject);
var
  ErrorCode: Integer;
begin
  ShellExec('open', 'https://npcap.com/#download', '', '', SW_SHOWNORMAL, ewNoWait, ErrorCode);
end;

procedure InitializeWizard();
var
  Info: TNewStaticText;
  OpenButton: TNewButton;
begin
  NpcapPage := CreateCustomPage(wpSelectTasks,
    'Npcap (packet-capture driver)',
    'PCAP bridged networking needs the free Npcap driver.');

  Info := TNewStaticText.Create(NpcapPage);
  Info.Parent := NpcapPage.Surface;
  Info.Left := 0;
  Info.Top := 0;
  Info.Width := NpcapPage.SurfaceWidth;
  Info.AutoSize := False;
  Info.WordWrap := True;
  Info.Height := ScaleY(96);
  Info.Caption :=
    'IRIS bridged (PCAP) networking requires Npcap, a free WinPcap-compatible driver. ' +
    'It is not bundled with IRIS and is not downloaded automatically.' + #13#10#13#10 +
    'Click the button below to open the Npcap download page in your browser. Install ' +
    'Npcap (its installer asks for Administrator), then return here and click Next — ' +
    'IRIS will re-check for the driver. You can also continue and install it later.';

  OpenButton := TNewButton.Create(NpcapPage);
  OpenButton.Parent := NpcapPage.Surface;
  OpenButton.Left := 0;
  OpenButton.Top := Info.Top + Info.Height + ScaleY(8);
  OpenButton.Width := ScaleX(240);
  OpenButton.Height := ScaleY(28);
  OpenButton.Caption := 'Open the Npcap download page';
  OpenButton.OnClick := @OpenNpcapSite;
end;

{ Skip the Npcap page when the driver is already present. }
function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  if (NpcapPage <> nil) and (PageID = NpcapPage.ID) then
    Result := NpcapInstalled();
end;

{ "Try again": re-check on Next. If still missing, let the user retry (stay on
  the page to install first) or continue without it. }
function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if (NpcapPage <> nil) and (CurPageID = NpcapPage.ID) and (not NpcapInstalled()) then
  begin
    if MsgBox(
        'Npcap was not detected yet. PCAP bridged networking will not work until it is installed.'
        + #13#10#13#10 +
        'Click Yes to re-check after installing Npcap (stay on this page), or No to continue '
        + 'and install it later.',
        mbConfirmation, MB_YESNO) = IDYES then
      Result := False;
  end;
end;
#endif
